### ISSUE TITLE
How do you get this thing running?

### ISSUE THREAD

**Issue by KarthickLinganathan** [koushik-elite/My-Survey-Builder#1]
I do not see any start scripts, Can you shed some light on installation steps?

**Comment by KarthickLinganathan** [comment]
I am getting this error after running "npm run build"

assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/sundaresanv/workspace/My-Survey-Builder/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/sundaresanv/workspace/My-Survey-Builder/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/sundaresanv/workspace/My-Survey-Builder/gulpfile.js:13:6)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
